#!/usr/bin/env python

''' 
    Rosalind Python Exercice ID: DNA
    Exercice name: Counting DNA Nucleotides
    URL: http://rosalind.info/problems/dna/
'''

DNA = "CCCCTACGCTGTTCCGAAGGCTTGCGCTAACCTCATTCTGTGTGGGTTTGAAATAGATTGACGGACCGTGGATGTGAGATGGCTAGTTTTTTGCGCCGACTAGATGAGCTAACTTTGGAACATAGCGCGAGTCTATTTCCTAACAGCGCAAAGTACTCTGCGCACTCCATCTCGTAGGTGGGGCGACATAGACTTTTCTATAGACGTAGACCTTGCATCCATCGGGGCTGGGGTGAGTATGTAGAGCTCGGGCACGCACTCACAATAAGTAGACGCCTCCTCAATACAAATCTAGAATTACGGATCTCTTGCGATGAAGAGGACATGTAACGGCTGGTCAAGTGACGCCTGCTAGCCAACCTACCTTTGCACGGTTTCCCGCATACGATACTAGACCTGAAGGGCCTCAATGAATCCATAAGCCCCTCCCGGAGTGGTTACGATTGTCCTGAGCTCGTGCCACAGCCATGTTGTCTGGCGGACCGCTCTCACCGCGAAATACTCTGGAAGCGATCAATCCCAACGCTCCCAGGTAAAATGGAAACATGCGATCATTTTATGACCAGCCGTCGGTGTGGTCCCTAAGGCACAATACCAACATAAGCGTTATCATTGGATTCACGCAATTCTTACACGATCTGGCCAAAAGCCTCACATCACATCAGGAATTTGGATACTGTAATATGCATCAACGCAGTACTCTCACGCGGGAGCTCTTCCGATACGGCTGACGTATGCAGGATTCCCGCAGATGCTCATGCACCTGGCGGGTCTTTTAGTAACAGCAGCATGGTGGACATTCCCTACCCTGGAGTGAGAGTATGGCTGAGCCTTCGTACGGCCATATACAGGAGAGCGCACTGCGTCGTGGAATTGGATCTTAGGTA"

print DNA

length = len(DNA)
print length

#count the number of Adenine in DNA sequence
count_A = DNA.count("A")

#count the number of Cytosine in DNA sequence
count_C = DNA.count("C")

#count the number of Guanine in DNA sequence
count_G = DNA.count("G")

#count the number of Thymine in DNA sequence
count_T = DNA.count("T")

print count_A , count_C , count_G , count_T
