#!/usr/bin/env python

"""
    Rosalind Python Exercice ID: REVC
    Exercice name: Complementing a Strand of DNA
    URL: http://rosalind.info/problems/revc
"""

# Constants
DNA = "TAGCGCGTAACATTATTGTGAGGTATCTTGAGTGAGCTATGGGAGCCATCGGGTCTGGTCGATGGAAGGCTCCTAAGTTGGAAGCCCGACTTGGGATCGGAGTTTTCTGAAAAGGAAGGTCAGACAACGACTGCGGGGCCTTGATTAGTAAATAATAGAAGTATTAAATGCGGGACATTCGAGATACGTGAAATCTTCTTGCATCGCGAGAGGCATTCCAAAATAAATGTATGATCTGGTGTTCCATGAGTCAGTCGGTGGCTGCTGCCACGTGTTATCAAATTTTAGCAAGGAGTGGCGTCCAAAAGAGACCCTAACCTATGCCCGTCCCCGAGAAAAGTCACTTGCGAGTCTTACCCCCTTCTGTGGAGGTGGACCTCGGACCTTACCTCCGGGTCGAGTGGATTGTGGGTCTTTTATGGTGTAGGTTCGATCACCGAGGCTCGACCGGGACGGCCGAAACGTGGAAACAGGCGGCCACCTAATGTAAGAATGCCTTCCCGTAAAGCTCTCCGACGAAAAGCCTGCGTGCTGGGACCTCGTGACTTGTATTCCGCGCGCCTTTACACCCGGATACCCAAACCGGGAAGGGGCCGTTGGAGCTGAAGGGTAACGGGTAGGATGAGGCCATTTTTGAACAGGCAGCCTTTTGTTCCATAAGGCTTGGAAACGAAATGACGCTAAGAAGCTCCCGTTATGTGGACCTCCTGCCTCAGGTAGGGGGGGTGTGTAGCAGAATGAGGAGCTATATACGGGCGAGCATTGCAAAGTACGCAGTTTATGTCGTGTGTTTCTAAACGG"
answer = []
complement = {'A':'T', 'T':'A', 'G':'C', 'C':'G'}

for nucleotide in DNA:
    answer.append(complement[nucleotide])

print ''.join(answer[::-1])